const actions = {
  GET_DOMAINS_REQUEST: 'GET_DOMAINS_REQUEST',
  GET_DOMAINS_SUCCESS: 'GET_DOMAINS_SUCCESS',
  UPDATE_DOMAINS: 'UPDATE_DOMAINS',

  UPDATE_DOMAIN_ID: 'UPDATE_DOMAIN_ID',
  UPDATE_DOMAIN_ID_SUCCESS: 'UPDATE_DOMAIN_ID_SUCCESS',

  GET_HOSTS_REQUEST: 'GET_HOSTS_REQUEST',
  GET_HOSTS_SUCCESS: 'GET_HOSTS_SUCCESS',
  UPDATE_HOSTS: 'UPDATE_HOSTS',

  UPDATE_HOST_ID: 'UPDATE_HOST_ID',
  UPDATE_HOST_ID_SUCCESS: 'UPDATE_HOST_ID_SUCCESS',

  GET_LINKBUILDER_REQUEST: 'GET_LINKBUILDER_REQUEST',
  GET_LINKBUILDER_SUCCESS: 'GET_LINKBUILDER_SUCCESS',
  CREATE_LINKBUILDER_REQUEST: 'CREATE_LINKBUILDER_REQUEST',
  CREATE_LINKBUILDER_SUCCESS: 'CREATE_LINKBUILDER_SUCCESS',
  UPDATE_LINKBUILDER: 'UPDATE_LINKBUILDER',

  GET_LINKBUILDER_CAMPAIGN_REQUEST: 'GET_LINKBUILDER_CAMPAIGN_REQUEST',
  GET_LINKBUILDER_CAMPAIGN_SUCCESS: 'GET_LINKBUILDER_CAMPAIGN_SUCCESS',
  CREATE_LINKBUILDER_CAMPAIGN_REQUEST: 'CREATE_LINKBUILDER_CAMPAIGN_REQUEST',
  CREATE_LINKBUILDER_CAMPAIGN_SUCCESS: 'CREATE_LINKBUILDER_CAMPAIGN_SUCCESS',
  UPDATE_LINKBUILDER_CAMPAIGN: 'UPDATE_LINKBUILDER_CAMPAIGN',

  GET_ACTIONS_REQUEST: 'GET_ACTIONS_REQUEST',
  GET_ACTIONS_SUCCESS: 'GET_ACTIONS_SUCCESS',
  UPDATE_ACTIONS: 'UPDATE_ACTIONS',

  GET_CONTENT_REQUEST: 'GET_CONTENT_REQUEST',
  GET_CONTENT_SUCCESS: 'GET_CONTENT_SUCCESS',
  UPDATE_CONTENT: 'UPDATE_CONTENT',

  GET_ATTRIBUTION_REQUEST: 'GET_ATTRIBUTION_REQUEST',
  GET_ATTRIBUTION_SUCCESS: 'GET_ATTRIBUTION_SUCCESS',
  UPDATE_ATTRIBUTION: 'UPDATE_ATTRIBUTION',

  GET_SETTINGS_REQUEST: 'GET_SETTINGS_REQUEST',
  GET_SETTINGS_SUCCESS: 'GET_SETTINGS_SUCCESS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',

  GET_ACCOUNT_REQUEST: 'GET_ACCOUNT_REQUEST',
  GET_ACCOUNT_SUCCESS: 'GET_ACCOUNT_SUCCESS',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',

  GET_OVERVIEW_REQUEST: 'GET_OVERVIEW_REQUEST',
  GET_OVERVIEW_SUCCESS: 'GET_OVERVIEW_SUCCESS',
  UPDATE_OVERVIEW: 'UPDATE_OVERVIEW',

  GET_CHARTDATA_REQUEST: 'GET_CHARTDATA_REQUEST',
  GET_CHARTDATA_REQUEST_SUCCESS: 'GET_CHARTDATA_REQUEST_SUCCESS',

  GET_TOOLTIP_PAGEDATA_REQUEST: 'GET_TOOLTIP_PAGEDATA_REQUEST',
  GET_TOOLTIP_PAGEDATA_REQUEST_SUCCESS: 'GET_TOOLTIP_PAGEDATA_REQUEST_SUCCESS',

  GET_TOOLTIP_SOURCEDATA_REQUEST: 'GET_TOOLTIP_SOURCEDATA_REQUEST',
  GET_TOOLTIP_SOURCEDATA_REQUEST_SUCCESS: 'GET_TOOLTIP_SOURCEDATA_REQUEST_SUCCESS',

  GET_TOOLTIP_DEVICEDATA_REQUEST: 'GET_TOOLTIP_DEVICEDATA_REQUEST',
  GET_TOOLTIP_DEVICEDATA_REQUEST_SUCCESS: 'GET_TOOLTIP_DEVICEDATA_REQUEST_SUCCESS',

  GET_TOP_COUNTRY_DATA_REQUEST:'GET_TOP_COUNTRY_DATA_REQUEST',
  GET_TOP_COUNTRY_DATA_REQUEST_SUCCESS:'GET_TOP_COUNTRY_DATA_REQUEST_SUCCESS',

  GET_PAGEDATA_REQUEST: 'GET_PAGEDATA_REQUEST',
  GET_PAGEDATA_REQUEST_SUCCESS: 'GET_PAGEDATA_REQUEST_SUCCESS',

  UPDATE_DATE_RANGE: 'UPDATE_DATE_RANGE',
  UPDATE_DATE_RANGE_SUCCESS: 'UPDATE_DATE_RANGE_SUCCESS',

  UPDATE_PARENT_DATA: 'UPDATE_PARENT_DATA',
  
  UPDATE_FILTER: 'UPDATE_FILTER',
  UPDATE_FILTER_SUCCESS: 'UPDATE_FILTER_SUCCESS',

  getDomains: () => ({ type: actions.GET_DOMAINS_REQUEST }),
  updateDomainId: (domainId) => ({ type: actions.UPDATE_DOMAIN_ID, domainId }),
  getHosts: (domainId) => ({ type: actions.GET_HOSTS_REQUEST, domainId }),
  updateHostId: (hostId) => ({ type: actions.UPDATE_HOST_ID, hostId }),
  getLinkBuilderRequest: (domainId) => ({
    type: actions.GET_LINKBUILDER_REQUEST,
    domainId,
  }),
  createLinkBuilderRequest: (links) => ({
    type: actions.CREATE_LINKBUILDER_REQUEST,
    links,
  }),
  getLinkBuilderCampaignRequest: (domainId, shortLinkId) => ({
    type: actions.GET_LINKBUILDER_CAMPAIGN_REQUEST,
    domainId,
    shortLinkId,
  }),
  createLinkBuilderCampaignRequest: (campaigns) => ({
    type: actions.CREATE_LINKBUILDER_CAMPAIGN_REQUEST,
    campaigns,
  }),

  getActionsRequest: () => ({ type: actions.GET_ACTIONS_REQUEST }),
  getContentRequest: (payload) => ({ 
    type: actions.GET_CONTENT_REQUEST,
    payload 
  }),
  getAttributionRequest: () => ({ type: actions.GET_ATTRIBUTION_REQUEST }),
  getSettingsRequest: () => ({ type: actions.GET_SETTINGS_REQUEST }),
  getAccountRequest: () => ({ type: actions.GET_ACCOUNT_REQUEST }),

  getOverviewRequest: () => ({ type: actions.GET_OVERVIEW_REQUEST }),
  getChartDataRequest: (payload) => ({ 
    type: actions.GET_CHARTDATA_REQUEST, 
    payload 
  }),
  getTooltipPageDataRequest: (payload) => ({ 
    type: actions.GET_TOOLTIP_PAGEDATA_REQUEST, 
    payload 
  }),
  getTooltipSourceDataRequest: (payload) => ({ 
    type: actions.GET_TOOLTIP_SOURCEDATA_REQUEST, 
    payload 
  }),
  getTooltipDeviceDataRequest: (payload) => ({ 
    type: actions.GET_TOOLTIP_DEVICEDATA_REQUEST, 
    payload 
  }),
  getTopCountryDataRequest: (payload) => ({ 
    type: actions.GET_TOP_COUNTRY_DATA_REQUEST, 
    payload 
  }),

  getPageDataRequest: (payload) => ({ 
    type: actions.GET_PAGEDATA_REQUEST, 
    payload 
  }),

  updateDateRange: (payload) => ({ type: actions.UPDATE_DATE_RANGE, payload }),
  updateParentData: (payload) => ({
    type: actions.UPDATE_PARENT_DATA,
    payload,
  }),

  updateFilter: (filter) => ({
    type: actions.UPDATE_FILTER,
    filter,
  }),
};
export default actions;
